### ISSUE TITLE
Please add a "FileHandler" Class 

### ISSUE THREAD

**Issue by Moshizzl3** [MathiasReker/Marios-Pizzabar#22]
#### Is your feature request related to a problem?

We need a FinleHandler class to handle the files

#### Describe the solution you'd like

We need a FileHandler class to handle loading and saving files

#### Alternatives you've considered

Database, but not within our knowledge yet.

#### Additional context

none

**Comment by MathiasReker** [comment]
Fixed by https://github.com/MathiasReker/Marios-Pizzabar/pull/30
