### ISSUE TITLE
Please add a config class/file

### ISSUE THREAD

**Issue by Moshizzl3** [MathiasReker/Marios-Pizzabar#24]
#### Is your feature request related to a problem?

We need a config file, to handle configuring the menu and maybe other stuff

#### Describe the solution you'd like

We should have a class that can handle the configuration of the program, there should also be a file that saves users config, and loads it once the program I booted.

#### Alternatives you've considered

We could not have it.

#### Additional context

No

**Comment by MathiasReker** [comment]
Fixed #35
